# Generated by Django 5.2.17 on 2026-08-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_google_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='calendar_retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appointment',
            name='calendar_sync_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='calendar_sync_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='email_notification_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
